In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

In [4]:
input_neurons = 2
hidden_neurons = 3
output_neurons = 1

np.random.seed(1)

wh = np.random.rand(input_neurons, hidden_neurons)
bh = np.random.rand(1, hidden_neurons)

wo = np.random.rand(hidden_neurons, output_neurons)
bo = np.random.rand(1, output_neurons)

learning_rate = 0.5
epochs = 5000

In [5]:
for i in range(epochs):

    # Forward Propagation
    hidden_input = np.dot(X, wh) + bh
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, wo) + bo
    predicted_output = sigmoid(final_input)

    # Back Propagation
    error = y - predicted_output
    d_output = error * sigmoid_derivative(predicted_output)

    error_hidden = d_output.dot(wo.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Update weights
    wo += hidden_output.T.dot(d_output) * learning_rate
    bo += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    wh += X.T.dot(d_hidden) * learning_rate
    bh += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate


# Output
print("Input:")
print(X)

print("\nExpected Output:")
print(y)

print("\nPredicted Output:")
print(predicted_output)

print("\nBinary Output:")
print((predicted_output > 0.5).astype(int))

Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Expected Output:
[[0]
 [1]
 [1]
 [0]]

Predicted Output:
[[0.02976436]
 [0.97198339]
 [0.97341712]
 [0.02883285]]

Binary Output:
[[0]
 [1]
 [1]
 [0]]
