In [1]:
import numpy as np

In [2]:
print("Hopfield Network Storing 4 Vectors\n")

x1 = np.array([1, -1, 1, -1])
x2 = np.array([1, 1, -1, -1])
x3 = np.array([-1, 1, 1, -1])
x4 = np.array([-1, -1, 1, 1])

Hopfield Network Storing 4 Vectors



In [3]:
patterns = np.array([x1, x2, x3, x4])

print("Stored Vectors:")
for i, p in enumerate(patterns):
    print("Vector", i+1, ":", p)

Stored Vectors:
Vector 1 : [ 1 -1  1 -1]
Vector 2 : [ 1  1 -1 -1]
Vector 3 : [-1  1  1 -1]
Vector 4 : [-1 -1  1  1]


In [4]:
n = patterns.shape[1]
weights = np.zeros((n, n))

for p in patterns:
    p = p.reshape(n, 1)
    weights += np.dot(p, p.T)

np.fill_diagonal(weights, 0)

print("\nWeight Matrix:")
print(weights)


Weight Matrix:
[[ 0.  0. -2. -2.]
 [ 0.  0. -2. -2.]
 [-2. -2.  0.  0.]
 [-2. -2.  0.  0.]]


In [5]:
def hopfield_recall(test, weights, steps=5):
    state = test.copy()
    for _ in range(steps):
        for i in range(len(state)):
            raw = np.dot(weights[i], state)
            state[i] = 1 if raw >= 0 else -1
    return state

In [6]:
print("\nEnter Test Vector Values (1 or -1)")
test_vector = []

for i in range(n):
    value = int(input("Enter value "+str(i+1)+": "))
    test_vector.append(value)

test_vector = np.array(test_vector)


Enter Test Vector Values (1 or -1)


Enter value 1:  1
Enter value 2:  -1
Enter value 3:  1
Enter value 4:  -1


In [7]:
print("\nInput Vector:")
print(test_vector)


Input Vector:
[ 1 -1  1 -1]


In [8]:
output = hopfield_recall(test_vector, weights)

print("\nRecalled Vector:")
print(output)


Recalled Vector:
[ 1  1 -1 -1]


In [9]:
print("\nComparison With Stored Vectors:")
for i, p in enumerate(patterns):
    print("Vector", i+1, ":", p, " Match:", np.array_equal(output, p))


Comparison With Stored Vectors:
Vector 1 : [ 1 -1  1 -1]  Match: False
Vector 2 : [ 1  1 -1 -1]  Match: True
Vector 3 : [-1  1  1 -1]  Match: False
Vector 4 : [-1 -1  1  1]  Match: False
