In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [4]:
input_layer_neurons = 2
hidden_layer_neurons = 2
output_neurons = 1

wh = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
bh = np.random.uniform(size=(1, hidden_layer_neurons))
wout = np.random.uniform(size=(hidden_layer_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))

lr = 0.5
epochs = 10000

In [6]:
for i in range(epochs):

    hidden_layer_input = np.dot(X, wh) + bh
    hidden_layer_activations = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_activations, wout) + bout
    predicted_output = sigmoid(output_layer_input)

    error = y - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(wout.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_activations)

    wout += hidden_layer_activations.T.dot(d_predicted_output) * lr
    bout += np.sum(d_predicted_output, axis=0, keepdims=True) * lr
    wh += X.T.dot(d_hidden_layer) * lr
    bh += np.sum(d_hidden_layer, axis=0, keepdims=True) * lr

print("Input:")
print(X)

print("\nExpected Output:")
print(y)

print("\nPredicted Output (Raw):")
print(predicted_output)

print("\nPredicted Output (Binary):")
print((predicted_output > 0.5).astype(int))

Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Expected Output:
[[0]
 [1]
 [1]
 [0]]

Predicted Output (Raw):
[[0.01293483]
 [0.98894586]
 [0.98895731]
 [0.01136452]]

Predicted Output (Binary):
[[0]
 [1]
 [1]
 [0]]
