In [1]:
import numpy as np

In [2]:
x1 = np.array([1, -1, 1, -1])
x2 = np.array([-1, 1, -1, 1])
x3 = np.array([1, 1, -1, -1])
x4 = np.array([-1, -1, 1, 1])

patterns = np.array([x1, x2, x3, x4])

n = patterns.shape[1]

In [3]:
W = np.zeros((n, n))

for p in patterns:
    p = p.reshape(n, 1)
    W = W + np.dot(p, p.T)

for i in range(n):
    W[i][i] = 0

print("Weight Matrix:")
print(W)

Weight Matrix:
[[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]


In [4]:
test = np.array([1, -1, 1, 1])

print("\nTest Input:")
print(test)


Test Input:
[ 1 -1  1  1]


In [5]:
for _ in range(5):
    net = np.dot(W, test)
    
    for i in range(len(net)):
        if net[i] > 0:
            test[i] = 1
        else:
            test[i] = -1

print("\nRecovered Pattern:")
print(test)


Recovered Pattern:
[-1 -1  1 -1]
